# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import reeve_pb2 as reeve__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reeve_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReeveControlStub:
    """Reeve intervention channel — bidirectional streaming control protocol.
    Agents connect here (port 4316) to receive commands and send acknowledgments.
    Observation data goes through the OTel channel (ports 4317/4318), not here.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlStream = channel.stream_stream(
                '/reeve.ReeveControl/ControlStream',
                request_serializer=reeve__pb2.AgentMessage.SerializeToString,
                response_deserializer=reeve__pb2.ControlMessage.FromString,
                _registered_method=True)


class ReeveControlServicer:
    """Reeve intervention channel — bidirectional streaming control protocol.
    Agents connect here (port 4316) to receive commands and send acknowledgments.
    Observation data goes through the OTel channel (ports 4317/4318), not here.

    """

    def ControlStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReeveControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ControlStream,
                    request_deserializer=reeve__pb2.AgentMessage.FromString,
                    response_serializer=reeve__pb2.ControlMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reeve.ReeveControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reeve.ReeveControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReeveControl:
    """Reeve intervention channel — bidirectional streaming control protocol.
    Agents connect here (port 4316) to receive commands and send acknowledgments.
    Observation data goes through the OTel channel (ports 4317/4318), not here.

    """

    @staticmethod
    def ControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/reeve.ReeveControl/ControlStream',
            reeve__pb2.AgentMessage.SerializeToString,
            reeve__pb2.ControlMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
